### ISSUE TITLE
Fresh Install Crashed MacBook Prod

### ISSUE THREAD

**Issue by davidneudorfer** [mist64/xhyve#5]
Ran `./xhyverun.sh` after a successful build and my computer restarted. Here is the dump of the error:
```
Anonymous UUID:       773E4F62-4F0E-CFF2-EB31-6AF23C41C959

Wed Jun 10 07:46:46 2015

*** Panic Report ***
panic(cpu 0 caller 0xffffff8001417cc2): Kernel trap at 0xffffff80014125f4, type 6=invalid opcode, registers:
CR0: 0x0000000080010033, CR2: 0x00007fff757c3ce0, CR3: 0x00000002f90000a4, CR4: 0x00000000001607e0
RAX: 0x0000000000000000, RBX: 0xffffff81bfead000, RCX: 0x00000000ffffffff, RDX: 0x00000000fffffffe
RSP: 0xffffff81ec26bb08, RBP: 0xffffff81ec26bb10, RSI: 0x000ffffffffff000, RDI: 0x000000038d35d000
R8:  0xffffff80014308a0, R9:  0x0000000000000000, R10: 0x0000000007fc00af, R11: 0x00000000f9af40b0
R12: 0x0000000000000004, R13: 0xffffff801fead140, R14: 0xffffff8001abf9d0, R15: 0xffffff8001a34640
RFL: 0x0000000000010006, RIP: 0xffffff80014125f4, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x00007fff757c3ce0, Error code: 0x0000000000000000, Fault CPU: 0x0

Backtrace (CPU 0), Frame : Return Address
0xffffff81ec26b7b0 : 0xffffff800132bda1 
0xffffff81ec26b830 : 0xffffff8001417cc2 
0xffffff81ec26b9f0 : 0xffffff8001434b73 
0xffffff81ec26ba10 : 0xffffff80014125f4 
0xffffff81ec26bb10 : 0xffffff80014308f0 
0xffffff81ec26bb30 : 0xffffff8001421631 
0xffffff81ec26bc10 : 0xffffff800143063d 
0xffffff81ec26bc60 : 0xffffff7f8351e78d 
0xffffff81ec26bcb0 : 0xffffff7f8351ea4e 
0xffffff81ec26bcd0 : 0xffffff7f8352446f 
0xffffff81ec26bd00 : 0xffffff80018b6bc4 
0xffffff81ec26bd50 : 0xffffff80018fe175 
0xffffff81ec26bdc0 : 0xffffff80013e26be 
0xffffff81ec26be10 : 0xffffff800133000c 
0xffffff81ec26be40 : 0xffffff80013149f3 
0xffffff81ec26be90 : 0xffffff800132531d 
0xffffff81ec26bf10 : 0xffffff80014031ea 
0xffffff81ec26bfb0 : 0xffffff8001435396 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleHV(1.0)[67545152-7361-3327-9B54-5C0B884357F3]@0xffffff7f8351d000->0xffffff7f83527fff

BSD process name corresponding to current thread: xhyve

Mac OS version:
14D136

Kernel version:
Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64
Kernel UUID: 4B3A11F4-77AA-3D27-A22D-81A1BC5B504D
Kernel slide:     0x0000000001000000
Kernel text base: 0xffffff8001200000
__HIB  text base: 0xffffff8001100000
System model name: MacBookPro11,1 (Mac-189A3D4F975D5FFC)

System uptime in nanoseconds: 2367372615670
last loaded kext at 1779759236612: com.apple.filesystems.cd9660	1.4.4 (addr 0xffffff7f83a98000, size 36864)
last unloaded kext at 393199875695: com.apple.driver.AppleIntelLpssI2C	2.0.56 (addr 0xffffff7f83348000, size 36864)
loaded kexts:
com.vmware.kext.vmioplug.14.1.3	14.1.3
com.vmware.kext.vmx86	0249.89.30
com.vmware.kext.vmnet	0249.89.30
com.vmware.kext.vsockets	90.6.0
com.vmware.kext.vmci	90.6.3
org.virtualbox.kext.VBoxNetAdp	4.3.20
org.virtualbox.kext.VBoxNetFlt	4.3.20
org.virtualbox.kext.VBoxUSB	4.3.20
org.virtualbox.kext.VBoxDrv	4.3.20
com.apple.filesystems.cd9660	1.4.4
com.apple.filesystems.smbfs	3.0.1
com.apple.driver.AppleMikeyHIDDriver	124
com.apple.filesystems.autofs	3.0
com.apple.driver.AudioAUUC	1.70
com.apple.iokit.IOBluetoothSerialManager	4.3.4f4
com.apple.driver.AGPM	110.19.5
com.apple.driver.ApplePlatformEnabler	2.2.0d4
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AppleUpstreamUserClient	3.6.1
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleHDA	272.18
com.apple.driver.AppleSMCLMU	2.0.7d0
com.apple.driver.AppleCameraInterface	5.33.0
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	4.3.4f4
com.apple.driver.AppleLPC	1.7.3
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHWAccess	1
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleIntelHD5000Graphics	10.0.6
com.apple.driver.AppleIntelFramebufferAzul	10.0.6
com.apple.driver.AppleThunderboltIP	2.0.2
com.apple.driver.AppleBacklight	170.7.4
com.apple.driver.AppleMCCSControl	1.2.11
com.apple.driver.AppleUSBTCButtons	240.2
com.apple.driver.AppleUSBTCKeyboard	240.2
com.apple.driver.AppleUSBCardReader	3.5.5
com.apple.driver.XsanFilter	404
com.apple.driver.AppleUSBHub	705.4.2
com.apple.iokit.IOAHCIBlockStorage	2.7.1
com.apple.driver.AppleAHCIPort	3.1.2
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0d1
com.apple.BootCache	36
com.apple.driver.AirPort.Brcm4360	930.37.3
com.apple.driver.AppleUSBXHCI	710.4.11
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	3.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	3.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	161
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	272.18
com.apple.kext.OSvKernDSPLib	1.15
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.AppleHDAController	272.18
com.apple.iokit.IOHDAFamily	272.18
com.apple.iokit.IOAudioFamily	203.3
com.apple.vecLib.kext	1.2.0
com.apple.iokit.IOBluetoothHostControllerUSBTransport	4.3.4f4
com.apple.iokit.IOUSBUserClient	705.4.0
com.apple.driver.IOPlatformPluginFamily	5.9.1d7
com.apple.iokit.IOSerialFamily	11
com.apple.iokit.IOBluetoothFamily	4.3.4f4
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOSurface	97.4
com.apple.AppleGraphicsDeviceControl	3.10.22
com.apple.iokit.IOAcceleratorFamily2	156.14
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.driver.AppleSMBusController	1.0.13d1
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.driver.AppleUSBMultitouch	245.2
com.apple.iokit.IOUSBHIDDriver	705.4.0
com.apple.iokit.IOSCSIBlockCommandsDevice	3.7.5
com.apple.iokit.IOUSBMassStorageClass	3.7.2
com.apple.iokit.IOSCSIArchitectureModelFamily	3.7.5
com.apple.driver.AppleUSBMergeNub	705.4.0
com.apple.driver.AppleUSBComposite	705.4.9
com.apple.driver.CoreStorage	471.20.7
com.apple.iokit.IOAHCIFamily	2.7.5
com.apple.driver.AppleThunderboltDPInAdapter	4.0.6
com.apple.driver.AppleThunderboltDPAdapterFamily	4.0.6
com.apple.driver.AppleThunderboltPCIDownAdapter	2.0.2
com.apple.driver.AppleThunderboltNHI	3.1.7
com.apple.iokit.IOThunderboltFamily	4.2.2
com.apple.iokit.IO80211Family	730.60
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.iokit.IOUSBFamily	720.4.4
com.apple.driver.AppleEFINVRAM	2.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	396
com.apple.iokit.IOStorageFamily	2.0
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	3.1
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
Model: MacBookPro11,1, BootROM MBP111.0138.B14, 2 processors, Intel Core i5, 2.6 GHz, 16 GB, SMC 2.16f68
Graphics: Intel Iris, Intel Iris, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x112), Broadcom BCM43xx 1.0 (7.15.166.24.3)
Bluetooth: Version 4.3.4f4 15601, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256F, 251 GB
USB Device: Internal Memory Card Reader
USB Device: iPhone
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Apple Internal Keyboard / Trackpad
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.2
```

**Comment by mehdideveloper** [comment]
Same problem here (OS X 10.10.3)
I just post the first part of crash log:

*** Panic Report ***
panic(cpu 0 caller 0xffffff800d217cc2): Kernel trap at 0xffffff800d2125f4, type 6=invalid opcode, registers:
CR0: 0x0000000080010033, CR2: 0x00007fff76ab2ce0, CR3: 0x000000012fae10f9, CR4: 0x00000000003607e0
RAX: 0x0000000000000000, RBX: 0xffffff80ef0e8000, RCX: 0x00000000ffffffff, RDX: 0x00000000fffffffe
RSP: 0xffffff8019573b08, RBP: 0xffffff8019573b10, RSI: 0x000ffffffffff000, RDI: 0x000000001e7ca000
R8:  0xffffff800d2308a0, R9:  0x0000000000000000, R10: 0x0000000007fc00ca, R11: 0xffffff80246d5540
R12: 0x0000000000000004, R13: 0xffffff801f35c480, R14: 0xffffff800d8bf9d0, R15: 0xffffff800d834640
RFL: 0x0000000000010006, RIP: 0xffffff800d2125f4, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x00007fff76ab2ce0, Error code: 0x0000000000000000, Fault CPU: 0x0

Backtrace (CPU 0), Frame : Return Address
0xffffff80195737b0 : 0xffffff800d12bda1 
0xffffff8019573830 : 0xffffff800d217cc2 
0xffffff80195739f0 : 0xffffff800d234b73 
0xffffff8019573a10 : 0xffffff800d2125f4 
0xffffff8019573b10 : 0xffffff800d2308f0 
0xffffff8019573b30 : 0xffffff800d221631 
0xffffff8019573c10 : 0xffffff800d23063d 
0xffffff8019573c60 : 0xffffff7f8f2ea78d 
0xffffff8019573cb0 : 0xffffff7f8f2eaa4e 
0xffffff8019573cd0 : 0xffffff7f8f2f046f 
0xffffff8019573d00 : 0xffffff800d6b6bc4 
0xffffff8019573d50 : 0xffffff800d6fe175 
0xffffff8019573dc0 : 0xffffff800d1e26be 
0xffffff8019573e10 : 0xffffff800d13000c 
0xffffff8019573e40 : 0xffffff800d1149f3 
0xffffff8019573e90 : 0xffffff800d12531d 
0xffffff8019573f10 : 0xffffff800d2031ea 
0xffffff8019573fb0 : 0xffffff800d235396 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleHV(1.0)[67545152-7361-3327-9B54-5C0B884357F3]@0xffffff7f8f2e9000->0xffffff7f8f2f3fff

BSD process name corresponding to current thread: xhyve

**Comment by garrickp** [comment]
+1

    Anonymous UUID:       EC7C741E-6118-59B5-C765-3F1F8A523943

    Wed Jun 10 07:37:31 2015

    *** Panic Report ***
    panic(cpu 0 caller 0xffffff801d217cc2): Kernel trap at 0xffffff801d2125f4, type 6=invalid opcode, registers:
    CR0: 0x0000000080010033, CR2: 0x00007fff72260ce0, CR3: 0x00000001ac71b0f0, CR4: 0x00000000001607e0
    RAX: 0x0000000000000000, RBX: 0xffffff80ff0cc000, RCX: 0x00000000ffffffff, RDX: 0x00000000fffffffe
    RSP: 0xffffff8126a7bb08, RBP: 0xffffff8126a7bb10, RSI: 0x000ffffffffff000, RDI: 0x000000017571a000
    R8:  0xffffff801d2308a0, R9:  0x0000000000000000, R10: 0x0000000007fc014a, R11: 0x00000000e58c8b8f
    R12: 0x0000000000000004, R13: 0xffffff802f7623c0, R14: 0xffffff801d8bf9d0, R15: 0xffffff801d834640
    RFL: 0x0000000000010006, RIP: 0xffffff801d2125f4, CS:  0x0000000000000008, SS:  0x0000000000000010
    Fault CR2: 0x00007fff72260ce0, Error code: 0x0000000000000000, Fault CPU: 0x0

    Backtrace (CPU 0), Frame : Return Address
    0xffffff8126a7b7b0 : 0xffffff801d12bda1
    0xffffff8126a7b830 : 0xffffff801d217cc2
    0xffffff8126a7b9f0 : 0xffffff801d234b73
    0xffffff8126a7ba10 : 0xffffff801d2125f4
    0xffffff8126a7bb10 : 0xffffff801d2308f0
    0xffffff8126a7bb30 : 0xffffff801d221631
    0xffffff8126a7bc10 : 0xffffff801d23063d
    0xffffff8126a7bc60 : 0xffffff7f9f2c778d
    0xffffff8126a7bcb0 : 0xffffff7f9f2c7a4e
    0xffffff8126a7bcd0 : 0xffffff7f9f2cd46f
    0xffffff8126a7bd00 : 0xffffff801d6b6bc4
    0xffffff8126a7bd50 : 0xffffff801d6fe175
    0xffffff8126a7bdc0 : 0xffffff801d1e26be
    0xffffff8126a7be10 : 0xffffff801d13000c
    0xffffff8126a7be40 : 0xffffff801d1149f3
    0xffffff8126a7be90 : 0xffffff801d12531d
    0xffffff8126a7bf10 : 0xffffff801d2031ea
    0xffffff8126a7bfb0 : 0xffffff801d235396
        Kernel Extensions in backtrace:
            com.apple.driver.AppleHV(1.0)[67545152-7361-3327-9B54-5C0B884357F3]@0xffffff7f9f2c6000->0xffffff7f9f2d0fff

    BSD process name corresponding to current thread: xhyve

    Mac OS version:
    14D136

    Kernel version:
    Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64
    Kernel UUID: 4B3A11F4-77AA-3D27-A22D-81A1BC5B504D
    Kernel slide:     0x000000001ce00000
    Kernel text base: 0xffffff801d000000
    __HIB  text base: 0xffffff801cf00000
    System model name: MacBookPro11,1 (Mac-189A3D4F975D5FFC)

    System uptime in nanoseconds: 91280925716308
    last loaded kext at 9030299186284: com.apple.driver.AppleMikeyHIDDriver 124 (addr 0xffffff7f9f87d000, size 20480)
    last unloaded kext at 4799311775461: com.apple.driver.AppleHIDKeyboard  176.2 (addr 0xffffff7f9ee49000, size 32768)
    loaded kexts:
    com.logitech.driver.LogiGamingMouseFilter   1
    net.tunnelblick.tap 2780
    net.tunnelblick.tun 2780
    org.virtualbox.kext.VBoxNetAdp  4.3.18
    org.virtualbox.kext.VBoxNetFlt  4.3.18
    org.virtualbox.kext.VBoxUSB 4.3.18
    org.virtualbox.kext.VBoxDrv 4.3.18
    com.driver.LogJoystick  2.0
    com.apple.driver.AppleMikeyHIDDriver    124
    com.apple.iokit.SCSITaskUserClient  3.7.5
    com.apple.filesystems.afpfs 11.0
    com.apple.nke.asp-tcp   8.0.0
    com.apple.filesystems.autofs    3.0
    com.apple.driver.ApplePlatformEnabler   2.2.0d4
    com.apple.driver.AGPM   110.19.5
    com.apple.driver.X86PlatformShim    1.0.0
    com.apple.iokit.IOBluetoothSerialManager    4.3.4f4
    com.apple.driver.AudioAUUC  1.70
    com.apple.driver.AppleUpstreamUserClient    3.6.1
    com.apple.driver.AppleOSXWatchdog   1
    com.apple.driver.AppleHDA   272.18
    com.apple.driver.AppleCameraInterface   5.33.0
    com.apple.driver.AppleThunderboltIP 2.0.2
    com.apple.iokit.IOUserEthernet  1.0.1
    com.apple.Dont_Steal_Mac_OS_X   7.0.0
    com.apple.driver.AppleHWAccess  1
    com.apple.driver.AppleHV    1
    com.apple.driver.AppleIntelSlowAdaptiveClocking 4.0.0
    com.apple.driver.AppleBacklight 170.7.4
    com.apple.driver.AppleMCCSControl   1.2.11
    com.apple.driver.AppleLPC   1.7.3
    com.apple.driver.AppleSMCLMU    2.0.7d0
    com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport 4.3.4f4
    com.apple.driver.AppleIntelHD5000Graphics   10.0.6
    com.apple.driver.AppleIntelFramebufferAzul  10.0.6
    com.apple.driver.AppleUSBTCButtons  240.2
    com.apple.driver.AppleUSBTCKeyboard 240.2
    com.apple.driver.AppleUSBCardReader 3.5.5
    com.apple.AppleFSCompression.AppleFSCompressionTypeDataless 1.0.0d1
    com.apple.AppleFSCompression.AppleFSCompressionTypeZlib 1.0.0d1
    com.apple.BootCache 36
    com.apple.driver.AppleUSBHub    705.4.2
    com.apple.driver.XsanFilter 404
    com.apple.iokit.IOAHCIBlockStorage  2.7.1
    com.apple.driver.AppleAHCIPort  3.1.2
    com.apple.driver.AirPort.Brcm4360   930.37.3
    com.apple.driver.AppleUSBXHCI   710.4.11
    com.apple.driver.AppleHPET  1.8
    com.apple.driver.AppleSmartBatteryManager   161.0.0
    com.apple.driver.AppleACPIButtons   3.1
    com.apple.driver.AppleRTC   2.0
    com.apple.driver.AppleSMBIOS    2.1
    com.apple.driver.AppleACPIEC    3.1
    com.apple.driver.AppleAPIC  1.7
    com.apple.nke.applicationfirewall   161
    com.apple.security.quarantine   3
    com.apple.security.TMSafetyNet  8
    com.apple.security.SecureRemotePassword 1.0
    com.apple.kext.triggers 1.0
    com.apple.driver.DspFuncLib 272.18
    com.apple.kext.OSvKernDSPLib    1.15
    com.apple.driver.AppleHDAController 272.18
    com.apple.iokit.IOHDAFamily 272.18
    com.apple.iokit.IOSlowAdaptiveClockingFamily    1.0.0
    com.apple.driver.AppleBacklightExpert   1.1.0
    com.apple.driver.AppleSMBusController   1.0.13d1
    com.apple.iokit.IOSerialFamily  11
    com.apple.driver.X86PlatformPlugin  1.0.0
    com.apple.driver.IOPlatformPluginFamily 5.9.1d7
    com.apple.driver.AppleSMC   3.1.9
    com.apple.iokit.IOBluetoothHostControllerUSBTransport   4.3.4f4
    com.apple.iokit.IOBluetoothFamily   4.3.4f4
    com.apple.iokit.IOUSBUserClient 705.4.0
    com.apple.iokit.IOSurface   97.4
    com.apple.iokit.IONDRVSupport   2.4.1
    com.apple.AppleGraphicsDeviceControl    3.10.22
    com.apple.iokit.IOAcceleratorFamily2    156.14
    com.apple.iokit.IOGraphicsFamily    2.4.1
    com.apple.iokit.IOAudioFamily   203.3
    com.apple.vecLib.kext   1.2.0
    com.apple.driver.AppleUSBMultitouch 245.2
    com.apple.iokit.IOUSBHIDDriver  705.4.0
    com.apple.iokit.IOSCSIBlockCommandsDevice   3.7.5
    com.apple.iokit.IOUSBMassStorageClass   3.7.2
    com.apple.iokit.IOSCSIArchitectureModelFamily   3.7.5
    com.apple.driver.AppleUSBMergeNub   705.4.0
    com.apple.driver.AppleUSBComposite  705.4.9
    com.apple.driver.CoreStorage    471.20.7
    com.apple.iokit.IOAHCIFamily    2.7.5
    com.apple.driver.AppleThunderboltDPInAdapter    4.0.6
    com.apple.driver.AppleThunderboltDPAdapterFamily    4.0.6
    com.apple.driver.AppleThunderboltPCIDownAdapter 2.0.2
    com.apple.driver.AppleThunderboltNHI    3.1.7
    com.apple.iokit.IOThunderboltFamily 4.2.2
    com.apple.iokit.IO80211Family   730.60
    com.apple.driver.mDNSOffloadUserClient  1.0.1b8
    com.apple.iokit.IONetworkingFamily  3.2
    com.apple.iokit.IOUSBFamily 720.4.4
    com.apple.driver.AppleEFINVRAM  2.0
    com.apple.driver.AppleEFIRuntime    2.0
    com.apple.iokit.IOHIDFamily 2.0.0
    com.apple.iokit.IOSMBusFamily   1.1
    com.apple.security.sandbox  300.0
    com.apple.kext.AppleMatch   1.0.0d1
    com.apple.driver.AppleKeyStore  2
    com.apple.driver.AppleMobileFileIntegrity   1.0.5
    com.apple.driver.AppleCredentialManager 1.0
    com.apple.driver.DiskImages 396
    com.apple.iokit.IOStorageFamily 2.0
    com.apple.iokit.IOReportFamily  31
    com.apple.driver.AppleFDEKeyStore   28.30
    com.apple.driver.AppleACPIPlatform  3.1
    com.apple.iokit.IOPCIFamily 2.9
    com.apple.iokit.IOACPIFamily    1.4
    com.apple.kec.Libm  1
    com.apple.kec.pthread   1
    com.apple.kec.corecrypto    1.0

**Comment by rimusz** [comment]
the same happened to me too

**Comment by AntonioMeireles** [comment]
fwiw - happened to me also, on 1st attempt to run... but not anymore (!) since. (rMBP 15, early 2013 / latest 10.10.4 beta)

**Comment by davidneudorfer** [comment]
Same issue on second run.

**Comment by ngocphamm** [comment]
Same here :( Kernel Panic about 20 mins ago.

rMBP 13" late 2012. OS X 10.10.3. I'm too afraid to try for the second time.

**Comment by mist64** [comment]
This is a problem with VirtualBox. You will run into this issue once VirtualBox has run before, since it messes up the CR4 state. There is nothing xhyve can do. :(

**Comment by bbucko** [comment]
Could it be fixed by VirtualBox? Maybe you should create a ticket as you know what's the problem.

**Comment by davidneudorfer** [comment]
@mist64 I don't mind removing VirtualBox. How would I go about resetting my CR4 state?

**Comment by davidneudorfer** [comment]
@AntonioMeireles Which issue can we use to track this problem? I've uninstalled VirtualBox following the [directions found on their website](https://www.virtualbox.org/manual/ch02.html#idp88679232) but I am still having the restart issue.

**Comment by mist64** [comment]
The issue should go after you restart...
